#!/bin/sh

if [ -e ../code/pull ] && ! [[ `pwd` =~ .*code$ ]] && [[ $1 != 1 ]]; then
	sh ../code/pull 1
else
	# result=`git fetch origin 2>&1`
	# [[ $result ]] && git merge origin/master

	git fetch origin
	git diff master origin/master --quiet || 
		git merge origin/master
fi
