#!/bin/sh

if [ -e ../code/push ] && ! [[ `pwd` =~ .*code$ ]] && [[ $1 != 1 ]]; then
	sh ../code/push 1
else
	git add -A .
	if !(git diff --cached --quiet && git diff origin/master --quiet); then
		git ci -m "fix" && git push origin master:master
	fi
fi
