/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com.data_work_Native */

#ifndef _Included_com.data_work_Native
#define _Included_com.data_work_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com.data_work_Native
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com.data_work_Native_test
  (JNIEnv *, jobject)
{
		
}

#ifdef __cplusplus
}
#endif
#endif
