#!/bin/sh

## 不使用 submodule
# push() {
# 	cd $1
# 	if [ "`git st -s`" ]; then
# 		echo "[pushing $1 ...]"
# 		sh push
# 		echo
# 	else
# 		echo "[pass $1]"
# 	fi
# 	cd ..
# }

# for file in *; do
# 	if [ -f $file/push ]; then
# 		push $file
# 	fi
# done


# 每个子模块都执行 sh push
git submodule foreach 'sh push; echo ||:'

echo "update parent:"
git add -A .
git ci -m "fix"

git push --recurse-submodules=on-demand
